import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import localFont from "next/font/local"
import "./globals.css"

const geist = localFont({
  src: [
    {
      path: "./fonts/Geist-Thin.woff2",
      weight: "100",
      style: "normal"
    },
    {
      path: "./fonts/Geist-ExtraLight.woff2",
      weight: "200",
      style: "normal"
    },
    {
      path: "./fonts/Geist-Light.woff2",
      weight: "300",
      style: "normal"
    },
    {
      path: "./fonts/Geist-Regular.woff2",
      weight: "400",
      style: "normal"
    },
    {
      path: "./fonts/Geist-Medium.woff2",
      weight: "500",
      style: "normal"
    },
    {
      path: "./fonts/Geist-SemiBold.woff2",
      weight: "600",
      style: "normal"
    },
    {
      path: "./fonts/Geist-Bold.woff2",
      weight: "700",
      style: "normal"
    },
    {
      path: "./fonts/Geist-ExtraBold.woff2",
      weight: "800",
      style: "normal"
    },
    {
      path: "./fonts/Geist-Black.woff2",
      weight: "900",
      style: "normal"
    }
  ]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`antialiased ${geist.className} font-geist`}>
        {children}
        <Toaster
          expand
          toastOptions={{
            classNames: {
              error: "!bg-red-100"
            }
          }}
          visibleToasts={5}
        />
      </body>
    </html>
  );
}
